name: CompatHelper
on:
  schedule:
    - cron: 0 0 * * *
    # Run every day at midnight.
    # Hope it's not too wasteful.
  workflow_dispatch:
jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - name: Pkg.add("CompatHelper")
        run: julia -e 'using Pkg; Pkg.add("CompatHelper")'
      - name: CompatHelper.main()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMPATHELPER_PRIV: ${{ secrets.DOCUMENTER_KEY }}
          # So need to set this manually ig (in repo settings)
          # This is from here
          # https://documenter.juliadocs.org/dev/man/hosting/#GitHub-Actions:~:text=TagBot%20%26%20tagged%20versions
          #
          # Same in TagBot.yml
          #
        run: julia -e 'using CompatHelper; CompatHelper.main()'
