name: Build & deploy docs

# Build docs when anything changes except tests/
on:
  push:
    branches:
      - main
    paths-ignore:
      - test/**
    tags: ['*']
  pull_request:

# See Tests.yml for explanations of options.

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - uses: julia-actions/cache@v1
      - run: julia --project=docs -e 'using Pkg; Pkg.instantiate()'
      - uses: julia-actions/julia-docdeploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
